export enum EventLifecycleStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
}

export enum EventProductionPhase {
  INQUIRY = 'INQUIRY',
  PLANNING = 'PLANNING',
  PRE_PRODUCTION = 'PRE_PRODUCTION',
  PRODUCTION = 'PRODUCTION',
  POST_PRODUCTION = 'POST_PRODUCTION',
  REVIEW = 'REVIEW',
  DELIVERY = 'DELIVERY',
  FINISHED = 'FINISHED',
}

export enum EventDateStatus {
  UNSCHEDULED = 'UNSCHEDULED',
  TENTATIVE = 'TENTATIVE',
  PARTIALLY_CONFIRMED = 'PARTIALLY_CONFIRMED',
  CONFIRMED = 'CONFIRMED',
  POSTPONED = 'POSTPONED',
}

export enum EventPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum EventSessionType {
  MEETING = 'MEETING',
  PRE_PRODUCTION = 'PRE_PRODUCTION',
  REHEARSAL = 'REHEARSAL',
  PHOTO_SESSION = 'PHOTO_SESSION',
  RECORDING = 'RECORDING',
  CEREMONY = 'CEREMONY',
  RECEPTION = 'RECEPTION',
  PRODUCTION = 'PRODUCTION',
  POST_PRODUCTION = 'POST_PRODUCTION',
  DELIVERY = 'DELIVERY',
  OTHER = 'OTHER',
}

export enum EventSessionStatus {
  TENTATIVE = 'TENTATIVE',
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  POSTPONED = 'POSTPONED',
}
