export enum DeliverableType {
  PHOTOS = 'PHOTOS',
  VIDEOS = 'VIDEOS',
  DIGITAL_ALBUM = 'DIGITAL_ALBUM',
  PRINTED_ALBUM = 'PRINTED_ALBUM',
  USB_DRIVE = 'USB_DRIVE',
  DOWNLOAD_LINK = 'DOWNLOAD_LINK',
  CUSTOM = 'CUSTOM',
}

export enum DeliverableStatus {
  DRAFT = 'DRAFT',
  IN_PROGRESS = 'IN_PROGRESS',
  READY = 'READY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  ARCHIVED = 'ARCHIVED',
}

export enum DeliveryMethod {
  DIGITAL_DOWNLOAD = 'DIGITAL_DOWNLOAD',
  PHYSICAL_SHIPPING = 'PHYSICAL_SHIPPING',
  IN_PERSON_PICKUP = 'IN_PERSON_PICKUP',
  COURIER = 'COURIER',
  THIRD_PARTY_SERVICE = 'THIRD_PARTY_SERVICE',
  OTHER = 'OTHER',
}
