export enum ContractStatus {
  DRAFT = 'DRAFT',
  PENDING_SIGNATURE = 'PENDING_SIGNATURE',
  PARTIALLY_SIGNED = 'PARTIALLY_SIGNED',
  EXECUTED = 'EXECUTED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  ARCHIVED = 'ARCHIVED',
}

export enum ContractTemplateType {
  SERVICE_AGREEMENT = 'SERVICE_AGREEMENT',
  MODEL_RELEASE = 'MODEL_RELEASE',
  INTELLECTUAL_PROPERTY = 'INTELLECTUAL_PROPERTY',
  EVENT_TERMS = 'EVENT_TERMS',
  CUSTOM = 'CUSTOM',
}

export enum ContractPartyRole {
  PROVIDER = 'PROVIDER',
  CLIENT = 'CLIENT',
  WITNESS = 'WITNESS',
  GUARANTOR = 'GUARANTOR',
  OTHER = 'OTHER',
}

export enum SignatureStatus {
  PENDING = 'PENDING',
  SIGNED = 'SIGNED',
  DECLINED = 'DECLINED',
  EXPIRED = 'EXPIRED',
}
