export enum PaymentStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  REFUNDED = 'REFUNDED',
  CANCELLED = 'CANCELLED',
  ARCHIVED = 'ARCHIVED',
}

export enum PaymentPlan {
  FULL_PAYMENT = 'FULL_PAYMENT',
  INSTALLMENTS = 'INSTALLMENTS',
  MILESTONE_BASED = 'MILESTONE_BASED',
  CUSTOM = 'CUSTOM',
}

export enum InstallmentStatus {
  PENDING = 'PENDING',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
}

export enum PaymentMethod {
  CASH = 'CASH',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CREDIT_CARD = 'CREDIT_CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  MANUAL_RECORD = 'MANUAL_RECORD',
  EXTERNAL_ADAPTER = 'EXTERNAL_ADAPTER',
  OTHER = 'OTHER',
}

export enum TransactionType {
  PAYMENT = 'PAYMENT',
  PARTIAL_PAYMENT = 'PARTIAL_PAYMENT',
  REFUND = 'REFUND',
  ADJUSTMENT = 'ADJUSTMENT',
}
